# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("DB_HOST", "db") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV.fetch("DB_USER", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  database: <%= ENV.fetch("DB_NAME", "app_production") %>

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: app_production

cable:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "app_production") %>

queue:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "app_production") %>

cache:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "app_production") %>